from flask import Flask, render_template
from noticia import Noticia, Estado

app = Flask(__name__)

lista_noticias = [
    Noticia(0, '05/04/2022', 'Lorem ipsum dolor sit amet consectetur.', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ullam corrupti nostrum iure sint numquam recusandae impedit delectus.', 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolores qui aspernatur id beatae. Dolorum qui velit, ipsum molestias ab eius soluta officiis, animi harum suscipit amet quos doloremque impedit hic?Voluptas non magnam reprehenderit.Lorem ipsum dolor sit amet consectetur adipisicing elit. Laboriosam eos culpa nobis quidem quasi voluptatum! Cupiditate perferendis eligendi et mollitia iste odio libero recusandae non molestiae. Voluptas non magnam reprehenderit.Lorem ipsum dolor sit amet consectetur adipisicing elit. Laboriosam eos culpa nobis quidem quasi voluptatum! Cupiditate perferendis eligendi et mollitia iste odio libero recusandae non molestiae. Voluptas non magnam reprehenderit.Lorem ipsum dolor sit amet consectetur adipisicing elit. Laboriosam eos culpa nobis quidem quasi voluptatum! Cupiditate perferendis eligendi et mollitia iste odio libero recusandae non molestiae. Voluptas non magnam reprehenderit.', 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolores qui aspernatur id beatae. Dolorum qui velit, ipsum molestias ab eius soluta officiis, animi harum suscipit amet quos doloremque impedit hic?Voluptas non magnam reprehenderit.Lorem ipsum dolor sit amet consectetur adipisicing elit. Laboriosam eos culpa nobis quidem quasi voluptatum! Cupiditate perferendis eligendi et mollitia iste odio libero recusandae non molestiae. Voluptas non magnam reprehenderit.Lorem ipsum dolor sit amet consectetur adipisicing elit. Laboriosam eos culpa nobis quidem quasi voluptatum! Cupiditate perferendis eligendi et mollitia iste odio libero recusandae non molestiae. Voluptas non magnam reprehenderit.Lorem ipsum dolor sit amet consectetur adipisicing elit. Laboriosam eos culpa nobis quidem quasi voluptatum! Cupiditate perferendis eligendi et mollitia iste odio libero recusandae non molestiae. Voluptas non magnam reprehenderit.', 'https://www.severianodealmeida.rs.gov.br/uploads/noticiascontroller/624/upload20200409151118.jpg'),
    Noticia(1, '15/04/2022', 'Lorem ipsum dolor sit amet consectetur.', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ullam corrupti nostrum iure sint numquam recusandae impedit delectus.', 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolores qui aspernatur id beatae. Dolorum qui velit, ipsum molestias ab eius soluta officiis, animi harum suscipit amet quos doloremque impedit hic?Voluptas non magnam reprehenderit.Lorem ipsum dolor sit amet consectetur adipisicing elit. Laboriosam eos culpa nobis quidem quasi voluptatum! Cupiditate perferendis eligendi et mollitia iste odio libero recusandae non molestiae. Voluptas non magnam reprehenderit.Lorem ipsum dolor sit amet consectetur adipisicing elit. Laboriosam eos culpa nobis quidem quasi voluptatum! Cupiditate perferendis eligendi et mollitia iste odio libero recusandae non molestiae. Voluptas non magnam reprehenderit.Lorem ipsum dolor sit amet consectetur adipisicing elit. Laboriosam eos culpa nobis quidem quasi voluptatum! Cupiditate perferendis eligendi et mollitia iste odio libero recusandae non molestiae. Voluptas non magnam reprehenderit.', 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolores qui aspernatur id beatae. Dolorum qui velit, ipsum molestias ab eius soluta officiis, animi harum suscipit amet quos doloremque impedit hic?Voluptas non magnam reprehenderit.Lorem ipsum dolor sit amet consectetur adipisicing elit. Laboriosam eos culpa nobis quidem quasi voluptatum! Cupiditate perferendis eligendi et mollitia iste odio libero recusandae non molestiae. Voluptas non magnam reprehenderit.Lorem ipsum dolor sit amet consectetur adipisicing elit. Laboriosam eos culpa nobis quidem quasi voluptatum! Cupiditate perferendis eligendi et mollitia iste odio libero recusandae non molestiae. Voluptas non magnam reprehenderit.Lorem ipsum dolor sit amet consectetur adipisicing elit. Laboriosam eos culpa nobis quidem quasi voluptatum! Cupiditate perferendis eligendi et mollitia iste odio libero recusandae non molestiae. Voluptas non magnam reprehenderit.', 'https://www.severianodealmeida.rs.gov.br/uploads/noticiascontroller/624/upload20200409151118.jpg'),
    Noticia(2, '25/04/2022', 'Lorem ipsum dolor sit amet consectetur.', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ullam corrupti nostrum iure sint numquam recusandae impedit delectus.', 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolores qui aspernatur id beatae. Dolorum qui velit, ipsum molestias ab eius soluta officiis, animi harum suscipit amet quos doloremque impedit hic?Voluptas non magnam reprehenderit.Lorem ipsum dolor sit amet consectetur adipisicing elit. Laboriosam eos culpa nobis quidem quasi voluptatum! Cupiditate perferendis eligendi et mollitia iste odio libero recusandae non molestiae. Voluptas non magnam reprehenderit.Lorem ipsum dolor sit amet consectetur adipisicing elit. Laboriosam eos culpa nobis quidem quasi voluptatum! Cupiditate perferendis eligendi et mollitia iste odio libero recusandae non molestiae. Voluptas non magnam reprehenderit.Lorem ipsum dolor sit amet consectetur adipisicing elit. Laboriosam eos culpa nobis quidem quasi voluptatum! Cupiditate perferendis eligendi et mollitia iste odio libero recusandae non molestiae. Voluptas non magnam reprehenderit.', 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolores qui aspernatur id beatae. Dolorum qui velit, ipsum molestias ab eius soluta officiis, animi harum suscipit amet quos doloremque impedit hic?Voluptas non magnam reprehenderit.Lorem ipsum dolor sit amet consectetur adipisicing elit. Laboriosam eos culpa nobis quidem quasi voluptatum! Cupiditate perferendis eligendi et mollitia iste odio libero recusandae non molestiae. Voluptas non magnam reprehenderit.Lorem ipsum dolor sit amet consectetur adipisicing elit. Laboriosam eos culpa nobis quidem quasi voluptatum! Cupiditate perferendis eligendi et mollitia iste odio libero recusandae non molestiae. Voluptas non magnam reprehenderit.Lorem ipsum dolor sit amet consectetur adipisicing elit. Laboriosam eos culpa nobis quidem quasi voluptatum! Cupiditate perferendis eligendi et mollitia iste odio libero recusandae non molestiae. Voluptas non magnam reprehenderit.', 'https://www.severianodealmeida.rs.gov.br/uploads/noticiascontroller/624/upload20200409151118.jpg')
]

@app.route('/')
def eu_apoio_debug_com_print():
    return render_template('home.html', noticias=lista_noticias)
    
@app.route('/info/<id>')
def info(id):
    for i in lista_noticias:
        if int(i.get_id()) == int(id):
            return render_template('info.html', noticia=lista_noticias[int(id)])
    return render_template('erro.html')

app.run(debug=True)